name: multiple jobs

on:
  workflow_dispatch:

job:
  jobs-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print job's name
        run: echo "Job 1"

  jobs-2:
    runs-on: macos-latest
    steps:
      - name: Print job's name
        run: echo "Job 2"


  jobs-3:
    runs-on: windows-latest
    steps:
      - name: Print job's name
        run: echo "Job 3"

  jobs-4:
    needs: [job-1, job-3]
    runs-on: ubuntu-latest
    steps:
      - name: Print job's name
        run: echo "Job 4"
